export default() => ({
  evaluacionDatos: {
    tipoDocumento: 1,
    documento: null,
    placa: null,
    categoriaVehiculo: null,
    telefono: null,
    tallerVehicular: null,
    email: null,
    codigoProducto: null,
    channel: 1,
    origen: 4,

  },
  datos: {
    categoriaVehiculo: null,
    telefono: null,
    documento: null,
    placa: null,
    codigoEntidad: null,
    tipoDocumento: null,
    codigoProducto: null,
    step: null,
    nombres: null,
    arrayOfertas: [],
    codigoProspecto: null,
    canalAtencion: 2,
    origen: 4,
    codigoEvaluacion: null,
    estadoProspecto: null,
    channel: 1,
    departamento: null,
    provincia: null,
    distrito: null,
    ubigeo: null,
    direccion: null,
    sectorEconomico: null,
    actividadEconomica: null,
    profesion: null,
    isCheckValorados: [],
    codigoEntidad: 1
  },
  openDialog: false,
  quizArray: null,
  arrayDatos: [],
  contratoDatos: {},
  arrayProductos: null,
  isSelectTaller: true,
  loadingEvaluacion: false,
  isBtnOferta: false,
  numberOfQuestions: 0,
  validationQuestions: [],
})
