import { codPage } from '~/enums/firma/pages'
export default () => ({
  estadoProspecto: null,
  arrayDocuments: [],
  terminos: false,
  step: codPage.LOADING_PROCESS,
  responseCode: '',
  numberOfQuestions: 0,
  validationQuestions: [],
  prospectus: {
    apellidoMaterno: '',
    apellidoPaterno: '',
    canalAtencion: 2,
    channel: 5,
    codRes: "00",
    codigoEntidad: 1,
    codigoCredito: 0,
    codigoEvaluacion: 0,
    codigoExpediente: 0,
    codigoProducto: '',
    codigoProspecto: 0,
    detallesCredito: {},
    documento: "",
    email: "",
    estadoProspecto: 0,
    nombres: "",
    origen: 4,
    placa: 0,
    telefono: "",
  },
  prospectusTest: {},
})
